#desc = "Physical Constant CODATA2019."
#keywords = ["physical", "constants", "codata"]
name = "PhysConsts"
uuid = "0ec285f8-91b7-5dbf-9bdf-a8c7fa63d820"
#repo = "https://github.com/LaGuer/PhysConsts.jl.git"
author = "La Guer"
license = "MIT"
version = "v0.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
#Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
#Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
#Julia = "0.6.4"
julia = ">=0.7"
JSON = "0.18, 0.19, 0.20, 0.21"
#Measurements = ">= 1.0.2"
#Unitful = ">= 0.15.0"
